# Output directories
h5ad_file: "combined_processed_adata.h5ad"  # This should be the given input
inputs_dir: "results"
results_dir: "results"

# Arguments for the DE analysis workflow
comparison_obs: "celltype"  # Column in obs group cells by for comparison
comparison_mode: "group_vs_rest"  # Options: 'pairwise', 'group_vs_rest', 'REFERENCE_vs_group' where REFERENCE is the name of a group in the comparison_obs column
# List of covariates to include in the model
covariates:
  - "sample"

# Where these workflows are installed
workflow_dir: "/workdir/aav4003/GenomicsWorkflows"
