channels:
  - conda-forge
  - bioconda
  - r

dependencies:
  - r-base=4.4
  - r-irkernel
  - notebook
  - jupyter
  - papermill
  - r-monocle3~=1.3.1
  - bioconductor-org.hs.eg.db~=3.20.0
  - bioconductor-org.mm.eg.db~=3.20.0
  - r-garnett~=0.2.8
  - zellkonverter
