channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconductor-mast~=1.32.0
  - r-base~=4.4
  - r-irkernel
  - bioconductor-zellkonverter~=1.16.0
  - bioconductor-biocparallel
  - bioconductor-scuttle~=1.16.0
  - bioconductor-scran~=1.34.0
  - r-lme4
  - notebook
  - jupyter
  - papermill
  - r-biocmanager
  - r-remotes
