channels:
  - conda-forge

dependencies:
  - python=3.11
  - ipykernel
  - notebook
  - jupyter
  - scanpy~=1.11
  - leidenalg~=0.1
  - python-igraph~=0.11
  - seaborn~=0.13
  - kneed~=0.8
  - papermill
