# Output directories
h5ad_file: "combined_processed_adata.h5ad"
inputs_dir: "results"
results_dir: "results"
annotated_h5ad_file: "CNV_annotated_adata.h5ad"  # Output file for CNV annotations

# Reference and mode configuration
reference_celltypes: "T-cells,B-Cells"  # Typically immune cell types, comma-separated
celltype_column: "celltype"  # Column name in the h5ad file that contains cell type labels
sample_column: "sample"  # Column name in the h5ad file that contains sample identifiers
per_sample: true  # Whether to run CNV calling per sample individually or on the entire dataset

# Where these workflows are installed
workflow_dir: "/workdir/aav4003/GenomicsWorkflows"
